export const {
  MYSQL_DB_HOST,
  MYSQL_DB_USER,
  MYSQL_DB_PASSWORD,
  MYSQL_DB_NAME,
  MYSQL_DB_PORT,
  SECRET_KEY,
  POSTGRES_DB_HOST,
  POSTGRES_DB_USER,
  POSTGRES_DB_PASSWORD,
  POSTGRES_DB_NAME,
  POSTGRES_DB_PORT,
  POSTGRES_DB_URL
} = process.env;

export const SALT_ROUNDS = parseInt(process.env.SALT_ROUNDS, 10);